const TodoItemTypes = {

    FETCH_TODO_ITEMS: 'FETCH_TODO_ITEMS',
    FETCH_TODO_ITEMS_SUCCESS: 'FETCH_TODO_ITEMS_SUCCESS',
    FETCH_TODO_ITEMS_FAILURE: 'FETCH_TODO_ITEMS_FAILURE',

    ADD_NEW_TODO_ITEM: 'ADD_NEW_TODO_ITEM',
    ADD_NEW_TODO_ITEM_SUCCESS: 'ADD_NEW_TODO_ITEM_SUCCESS',

    EDIT_TODO_ITEM: 'EDIT_TODO_ITEM',
    EDIT_TODO_ITEM_SUCCESS: 'EDIT_TODO_ITEM_SUCCESS',

    DELETE_TODO_ITEM: 'DELETE_TODO_ITEM',
    DELETE_TODO_ITEM_SUCCESS: 'DELETE_TODO_ITEM_SUCCESS',

    TOOGLE_TODO_ITEM_COMPLETED: 'TOOGLE_TODO_ITEM_COMPLETED',
    TOOGLE_TODO_ITEM_COMPLETED_SUCCESS: 'TOOGLE_TODO_ITEM_COMPLETED_SUCCESS',

    CLEAR_TODO_ITEM_COMPLETED: 'CLEAR_TODO_ITEM_COMPLETED',
    CLEAR_TODO_ITEM_COMPLETED_SUCCESS: 'CLEAR_TODO_ITEM_COMPLETED_SUCCESS',

    CLEAR_COMPLETED: 'CLEAR_COMPLETED',
    CLEAR_COMPLETED_SUCCESS: 'CLEAR_COMPLETED_SUCCESS',

    TOGGLE_COMPLETED_ALL: 'TOGGLE_COMPLETED_ALL',
    TOGGLE_COMPLETED_ALL_SUCCESS: 'TOGGLE_COMPLETED_ALL_SUCCESS'


}

export default TodoItemTypes;